### ISSUE TITLE
Create Key Evidence Assets

### ISSUE THREAD

**Issue by AMastryukov** [AMastryukov/LD50#28]
Create the following Key Evidence 3D assets:

- [x] Red sedan, missing side view mirror, open trunk
- [x] Red car’s missing side view mirror
- [x] Signed Baseball
- [x] Brick of Cocaine
- [x] Box of Donuts
- [x] Gold Wristwatch
- [x] Cigar (lit & unlit)
- [x] Ripped Note
- [x] Playing Cards
- [x] Poker Chips
- [x] Teacup
- [x] Tea Tin
- [x] Revolver
- [x] Police badge
- [x] Police file
- [x] Cigar

**Comment by VastAppsInc** [comment]
You can use cigar mesh I passed on to Axel.  It was supposed to be used for the fatgangster
