### ISSUE TITLE
Create Environment Props

### ISSUE THREAD

**Issue by AMastryukov** [AMastryukov/LD50#29]
Create static environment props to fill in the levels and make them more believable and alive.

- [x] Dumpster
- [x] Black garbage bag
- [x] Trash can
- [x] Metal shelf
- [x] Car tire
- [x] Generic rectangular table
- [x] Circular poker table
- [x] Open suitcase
- [x] Closet
- [x] Bed
- [x] Bookshelf
- [x] Kitchen counter
- [x] Kitchen sink
- [x] Oven
- [x] Chair
- [x] Vertical file cabinet
- [x] Toolbox

**Comment by VastAppsInc** [comment]
all props on the list is low poly and already sent to Axel
