### ISSUE TITLE
Create Dynamic Props

### ISSUE THREAD

**Issue by AMastryukov** [AMastryukov/LD50#30]
Create dynamic props that the player can inspect, but that do not play an important role as key evidence.

- [x] Wad of cash
- [x] Coffee cup
- [x] Beer can/soda can
- [x] Newspaper
- [x] Book
- [x] Knife
- [x] Crowbar
- [x] Bottle
- [x] Broken bottle
- [x] Handcuffs
- [x] Table lamp
- [x] Clipboard
- [x] Ash tray
- [x] Telephone
- [x] Wrench
- [x] Headphones
- [x] Glass cup
- [x] Glasses
- [x] Mug
- [x] Duct tape
- [x] Crumpled paper
- [x] Video camera (90s/2000s)
- [x] Lighter
- [x] Cigarette butt
- [x] Pill bottle
- [x] Brick
- [x] Floppy disk
- [x] Syringe
- [x] Bat
- [x] Dumbbell
- [x] Plant pot
- [x] Shoe
- [x] Glove
- [x] Cardboard box

**Comment by VastAppsInc** [comment]
Sent Dynamic Props to Axel for review

**Comment by VastAppsInc** [comment]
finished all assets in the dynamic prop list

**Comment by VastAppsInc** [comment]
finished texturing all assets i sent to Axel earlier and his unique texture.
